// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Next.js conventionally keeps local secrets in `.env.local`; load it here so
// the Prisma CLI (migrate/generate/studio) sees the same DATABASE_URL as the app.
// `quiet` suppresses dotenv's promotional console tips.
config({ path: ".env.local", quiet: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // The CLI (migrate/db pull/studio) talks directly to Postgres, bypassing
    // the pooler. Prisma Client at runtime uses DATABASE_URL (pooled) instead,
    // via the @prisma/adapter-neon driver adapter — see lib/db/prisma.ts.
    url: process.env["DIRECT_URL"],
  },
});
